version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build: .
    restart: always
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: root
      DB_NAME: library_db
      PORT: 3000
      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASS: secret
      RATE_LIMIT_WINDOW_MS: 60000
      RATE_LIMIT_MAX_REQUESTS: 5
    command: sh -c "node app.js"

volumes:
  mysql_data:
